version: "3"
services:
  engine:
    build: ./engine
    image: kpsarakis/schema-matching-engine:0.1
    ports:
      - "5000:5000"
    env_file:
      - redis.env
      - minio.env
    restart: always
    depends_on:
      - redis-db-matches
      - minio

  redis-db-matches:
    image: redis:latest
    env_file:
      - redis.env

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    volumes:
      - ./minio-volume:/mnt/data
    env_file:
      - minio.env
    command: server /mnt/data
