version: "3"
services:
  engine:
    image: kpsarakis/schema-matching-engine:0.1
    ports:
      - "5000:5000"
    env_file:
      - redis.env
      - minio.env
  redis-db-matches:
    image: redis:latest
    env_file:
      - redis.env
  minio:
    image: minio/minio:latest
    env_file:
      - minio.env