apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: kpsarakis/schema-matching-engine:latest
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "1"
          command: ["celery"]
          args: ["worker", "-A", "app.celery", "--concurrency=4", "--loglevel=info"]
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-master
            - name: REDIS_PORT
              value: '6379'
            - name: REDIS_PASSWORD
              value: "redis"
            - name: CELERY_RESULTS_MONGO_HOST
              value: mongodb
            - name: CELERY_RESULTS_MONGO_PORT
              value: '27017'
            - name: MINIO_HOST
              value: minio
            - name: MINIO_PORT
              value: '9000'
            - name: MINIO_ACCESS_KEY
              value: "minio"
            - name: MINIO_SECRET_KEY
              value: "minio123"