apiVersion: v1
kind: Service
metadata:
  name: flower-service
spec:
  type: NodePort
  selector:
    component: flower
  ports:
    - port: 5555
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: flower
  template:
    metadata:
      labels:
        component: flower
    spec:
      containers:
        - name: flower
          image: kpsarakis/schema-matching-engine:latest
          command: ['celery']
          args: ['flower', '-A', 'app.celery', 'flower']
          ports:
            - containerPort: 5555
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: RABBITMQ_HOST
              value: rabbitmq-cluster-ip-service
            - name: RABBITMQ_PORT
              value: '5672'
            - name: RABBITMQ_DEFAULT_USER
              value: "rabbitmq"
            - name: RABBITMQ_DEFAULT_PASS
              value: "rabbitmq"
            - name: CELERY_RESULTS_REDIS_HOST
              value: celery-results-backend-cluster-ip-service
            - name: CELERY_RESULTS_REDIS_PORT
              value: '6379'