apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-cluster-ip-service
spec:
  type: NodePort
  selector:
    component: rabbitmq
  ports:
    - name: mq
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: rabbitmq
  template:
    metadata:
      labels:
        component: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
            requests:
              memory: "2Gi"
              cpu: "1"
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "rabbitmq"
            - name: RABBITMQ_DEFAULT_PASS
              value: "rabbitmq"