apiVersion: v1
kind: Service
metadata:
  name: celery-results-backend-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: redis-celery
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-celery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis-celery
  template:
    metadata:
      labels:
        component: redis-celery
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379