apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: redis-matches
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-matches-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis-matches
  template:
    metadata:
      labels:
        component: redis-matches
    spec:
      containers:
        - name: redis
          image: redis
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 6379