apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: kpsarakis/schema-matching-engine:latest
          command: ["gunicorn"] # Need to configure threads, w and t
          args: ["-b", "0.0.0.0:5000", "app:app", "-t", "60", "-w", "1", "--threads", "1"]
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: RABBITMQ_HOST
              value: rabbitmq-cluster-ip-service
            - name: RABBITMQ_PORT
              value: '5672'
            - name: RABBITMQ_DEFAULT_USER
              value: "rabbitmq"
            - name: RABBITMQ_DEFAULT_PASS
              value: "rabbitmq"
            - name: CELERY_RESULTS_REDIS_HOST
              value: celery-results-backend-cluster-ip-service
            - name: CELERY_RESULTS_REDIS_PORT
              value: '6379'
            - name: MINIO_HOST
              value: minio
            - name: MINIO_PORT
              value: '9000'
            - name: MINIO_ACCESS_KEY
              value: "minio"
            - name: MINIO_SECRET_KEY
              value: "minio123"