apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: kpsarakis/schema-matching-engine:latest
          command: ["gunicorn -b 0.0.0.0:5000 app:app -t 60 -w 1 --threads 1"] # Need to configure threads, w and t
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: CELERY_BROKER_URL
              value: "amqp://rabbitmq:rabbitmq@celery-rabbitmq:5672/" # FIXME
            - name: CELERY_RESULT_BACKEND_URL
              value: "redis://redis-celery-results-backend:6379/" # FIXME
            - name: MINIO_HOST
              value: minio-cluster-ip-service
            - name: MINIO_PORT
              value: '9000'
            - name: MINIO_ACCESS_KEY
              value: "minio"
            - name: MINIO_SECRET_KEY
              value: "minio123"